export const PRODUCTS = [
  {
    "id": 1,
    "name": "Wireless Bluetooth Headphones",
    "description": "High-quality over-ear Bluetooth headphones with active noise cancellation and up to 30 hours of battery life.",
    "price": 99.99,
    "category": "electronics",
    "stock": 120,
    "rating": 4.5,
    "brand": "SoundMax",
    "color": "Black",
    "weight": "250g",
    "dimensions": "15 x 10 x 20 cm",
    "imageUrl": "https://example.com/product-images/headphones.jpg"
  },
  {
    "id": 2,
    "name": "Stainless Steel Insulated Water Bottle",
    "description": "A 500ml BPA-free stainless steel bottle that keeps drinks cold for 24 hours and hot for 12 hours.",
    "price": 19.99,
    "category": "home & kitchen",
    "stock": 50,
    "rating": 4.7,
    "brand": "EcoHydro",
    "color": "Silver",
    "weight": "350g",
    "dimensions": "7 x 7 x 25 cm",
    "imageUrl": "https://example.com/product-images/water-bottle.jpg"
  },
  {
    "id": 3,
    "name": "Organic Cotton T-Shirt",
    "description": "A soft, comfortable organic cotton t-shirt, available in multiple sizes and colors.",
    "price": 25.00,
    "category": "clothing",
    "stock": 200,
    "rating": 4.3,
    "brand": "GreenWear",
    "color": "White",
    "size": "M",
    "weight": "180g",
    "dimensions": "30 x 20 x 1 cm",
    "imageUrl": "https://example.com/product-images/t-shirt.jpg"
  },
  {
    "id": 4,
    "name": "4K Ultra HD Smart TV",
    "description": "65-inch 4K Ultra HD Smart TV with built-in streaming apps and voice control.",
    "price": 799.99,
    "category": "electronics",
    "stock": 20,
    "rating": 4.8,
    "brand": "VisionTech",
    "color": "Black",
    "weight": "18 kg",
    "dimensions": "145 x 25 x 85 cm",
    "imageUrl": "https://example.com/product-images/tv.jpg"
  },
  {
    "id": 5,
    "name": "Gaming Mouse with RGB Lighting",
    "description": "Ergonomic gaming mouse with customizable buttons, adjustable DPI settings, and RGB lighting.",
    "price": 49.99,
    "category": "electronics",
    "stock": 75,
    "rating": 4.6,
    "brand": "GamerPro",
    "color": "Black",
    "weight": "110g",
    "dimensions": "12 x 7 x 4 cm",
    "imageUrl": "https://example.com/product-images/mouse.jpg"
  },
    {
      "id": 6,
      "name": "Wireless Charging Pad",
      "description": "A fast-charging wireless pad compatible with all Qi-enabled devices, providing up to 15W charging speed.",
      "price": 29.99,
      "category": "electronics",
      "stock": 150,
      "rating": 4.4,
      "brand": "ChargeMaster",
      "color": "White",
      "weight": "150g",
      "dimensions": "10 x 10 x 1 cm",
      "imageUrl": "https://example.com/product-images/charging-pad.jpg"
    },
    {
      "id": 7,
      "name": "Leather Office Chair",
      "description": "Ergonomic high-back office chair with adjustable height and tilt, padded armrests, and breathable leather upholstery.",
      "price": 249.99,
      "category": "furniture",
      "stock": 35,
      "rating": 4.2,
      "brand": "ErgoComfort",
      "color": "Brown",
      "weight": "12 kg",
      "dimensions": "70 x 70 x 120 cm",
      "imageUrl": "https://example.com/product-images/office-chair.jpg"
    },
    {
      "id": 8,
      "name": "Noise-Cancelling Earbuds",
      "description": "Compact wireless earbuds with active noise cancellation and a charging case that provides up to 24 hours of playtime.",
      "price": 149.99,
      "category": "electronics",
      "stock": 85,
      "rating": 4.7,
      "brand": "AudioPulse",
      "color": "White",
      "weight": "50g",
      "dimensions": "5 x 3 x 2 cm",
      "imageUrl": "https://example.com/product-images/earbuds.jpg"
    },
    {
      "id": 9,
      "name": "Adjustable Standing Desk",
      "description": "A height-adjustable desk with a smooth electric lift system, capable of supporting up to 100kg and offering programmable height settings.",
      "price": 599.99,
      "category": "furniture",
      "stock": 20,
      "rating": 4.8,
      "brand": "WorkSmart",
      "color": "Oak",
      "weight": "45 kg",
      "dimensions": "140 x 75 x 110 cm",
      "imageUrl": "https://example.com/product-images/standing-desk.jpg"
    },
    {
      "id": 10,
      "name": "Smartwatch with Heart Rate Monitor",
      "description": "A sleek and durable smartwatch featuring GPS tracking, heart rate monitoring, and sleep analysis, with up to 10 days of battery life.",
      "price": 199.99,
      "category": "electronics",
      "stock": 70,
      "rating": 4.6,
      "brand": "FitSmart",
      "color": "Black",
      "weight": "70g",
      "dimensions": "4.5 x 4.5 x 1 cm",
      "imageUrl": "https://example.com/product-images/smartwatch.jpg"
    },
    {
      "id": 11,
      "name": "Yoga Mat with Carrying Strap",
      "description": "Eco-friendly, non-slip yoga mat made from recycled materials, offering extra padding for a comfortable workout.",
      "price": 34.99,
      "category": "sports & outdoors",
      "stock": 120,
      "rating": 4.5,
      "brand": "ZenGear",
      "color": "Green",
      "weight": "1.5 kg",
      "dimensions": "180 x 60 x 0.6 cm",
      "imageUrl": "https://example.com/product-images/yoga-mat.jpg"
    },
    {
      "id": 12,
      "name": "Portable Outdoor Projector",
      "description": "Compact, high-resolution projector with 1080p output, 2000 lumens, and up to 120-inch display, perfect for outdoor movie nights.",
      "price": 299.99,
      "category": "electronics",
      "stock": 25,
      "rating": 4.3,
      "brand": "VisionBeam",
      "color": "Silver",
      "weight": "2 kg",
      "dimensions": "20 x 15 x 8 cm",
      "imageUrl": "https://example.com/product-images/projector.jpg"
    },
    {
      "id": 13,
      "name": "Bamboo Cutting Board Set",
      "description": "Set of three eco-friendly bamboo cutting boards in various sizes, ideal for chopping vegetables, fruits, and meats.",
      "price": 49.99,
      "category": "home & kitchen",
      "stock": 100,
      "rating": 4.9,
      "brand": "EcoChef",
      "color": "Natural Bamboo",
      "weight": "2 kg",
      "dimensions": "40 x 30 x 2 cm",
      "imageUrl": "https://example.com/product-images/cutting-board.jpg"
    },
    {
      "id": 14,
      "name": "Cordless Electric Drill",
      "description": "18V cordless electric drill with two-speed settings and a rechargeable battery, perfect for DIY and home improvement projects.",
      "price": 89.99,
      "category": "tools & home improvement",
      "stock": 40,
      "rating": 4.6,
      "brand": "PowerFix",
      "color": "Blue",
      "weight": "1.5 kg",
      "dimensions": "20 x 8 x 22 cm",
      "imageUrl": "https://example.com/product-images/drill.jpg"
    },
    {
      "id": 15,
      "name": "Electric Toothbrush with 5 Modes",
      "description": "Rechargeable electric toothbrush with 5 brushing modes and a 2-minute timer for optimal dental care.",
      "price": 59.99,
      "category": "health & personal care",
      "stock": 150,
      "rating": 4.4,
      "brand": "BrightSmile",
      "color": "White",
      "weight": "200g",
      "dimensions": "25 x 3 x 3 cm",
      "imageUrl": "https://example.com/product-images/toothbrush.jpg"
    }
  ]
  